import { dashboardIsConfigured, hasEditorialSession } from "@/lib/editorial-dashboard/auth";
import { listD1InternalArticles } from "@/lib/d1/internal-client";
import { classifyD1EditorialInput } from "@/lib/d1/editorial/classify";
import { approveOne, approveSelected, login, logout, rejectOne, rejectSelected } from "./actions";

export const dynamic = "force-dynamic";

function string(value: unknown) { return typeof value === "string" ? value : ""; }
function formatDate(value: unknown) { const date = new Date(string(value)); return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat("es-UY", { dateStyle: "medium", timeStyle: "short" }).format(date) : "Sin fecha"; }

export default async function EditorialPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const configured = dashboardIsConfigured(); const authenticated = await hasEditorialSession(); const params = await searchParams;
  if (!configured) return <main className="mx-auto max-w-2xl p-8"><h1 className="text-2xl font-bold">Dashboard editorial no configurado</h1><p className="mt-3 text-slate-600">Faltan variables privadas de servidor. Esta ruta no expone datos ni permite acciones hasta que estén configuradas.</p></main>;
  if (!authenticated) return <main className="mx-auto max-w-md p-8"><h1 className="text-2xl font-bold">Revisión editorial</h1><p className="mt-2 text-slate-600">Acceso privado para revisar noticias pendientes.</p>{params.error ? <p className="mt-4 rounded bg-red-50 p-3 text-red-700">Contraseña incorrecta.</p> : null}<form action={login} className="mt-6 space-y-3"><label className="block text-sm font-medium" htmlFor="password">Contraseña</label><input id="password" name="password" type="password" required className="w-full rounded border p-2" autoComplete="current-password"/><button className="rounded bg-slate-900 px-4 py-2 text-white">Ingresar</button></form></main>;
  const response = await listD1InternalArticles({ editorialStatus: "pending_review", editorialReviewStatus: "pending", pageSize: 100 });
  const articles = response.data;
  return <main className="mx-auto max-w-6xl p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Bandeja de revisión editorial</h1><p className="mt-1 text-slate-600">{articles.length} noticias pendientes. Aprobar publica; rechazar conserva para auditoría.</p></div><form action={logout}><button className="rounded border px-3 py-2 text-sm">Salir</button></form></div><form className="mt-6 space-y-4"><div className="flex gap-3"><button formAction={approveSelected} className="rounded bg-emerald-700 px-4 py-2 font-medium text-white">Aprobar seleccionadas</button><button formAction={rejectSelected} className="rounded bg-red-700 px-4 py-2 font-medium text-white">Rechazar seleccionadas</button></div>{articles.map((raw) => { const article = { id: string(raw.id), slug: string(raw.slug), title: string(raw.title), excerpt: string(raw.excerpt), source_name: string(raw.source_name), source_url: string(raw.source_url), published_at: string(raw.published_at) }; const suggested = classifyD1EditorialInput(article); return <article key={article.slug} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><input type="checkbox" name="slug" value={article.slug} aria-label={`Seleccionar ${article.title}`} className="mt-1 h-5 w-5"/><div className="min-w-0 flex-1"><h2 className="text-lg font-semibold">{article.title}</h2><p className="mt-1 text-sm text-slate-600"><a href={article.source_url} target="_blank" rel="noreferrer" className="underline">{article.source_name || "Fuente original"}</a> · {formatDate(article.published_at)}</p><p className="mt-3 text-sm text-slate-700">{article.excerpt || "Sin extracto disponible."}</p><p className="mt-3 text-sm"><strong>Sugerido:</strong> {suggested.category} · {suggested.region} · {suggested.country ?? "sin país"} · tema: {suggested.topic_slug} · confianza: {suggested.evidence_terms.length >= 3 ? "alta" : suggested.evidence_terms.length ? "media" : "baja"}</p><p className="mt-1 text-xs text-slate-500">Reglas: {suggested.evidence_terms.join(", ") || "sin evidencia suficiente"}</p><div className="mt-4 flex gap-2"><button formAction={approveOne} name="oneSlug" value={article.slug} className="rounded bg-emerald-700 px-3 py-2 text-sm text-white">Aprobar</button><button formAction={rejectOne} name="oneSlug" value={article.slug} className="rounded bg-red-700 px-3 py-2 text-sm text-white">Rechazar</button></div></div></div></article>; })}</form></main>;
}
