-- D1/SQLite equivalent of Supabase migration 20260214_0001_articles.sql.
-- UUIDs are generated by TypeScript/Workers before insert; D1 has no pgcrypto.
-- Dates are UTC ISO-8601 TEXT values and array values are JSON TEXT.
CREATE TABLE IF NOT EXISTS articles (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  excerpt TEXT NOT NULL,
  content TEXT,
  image_url TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_url TEXT NOT NULL UNIQUE,
  region TEXT NOT NULL CHECK (region IN ('Mundo', 'LatAm', 'EE.UU.', 'Europa', 'Asia', 'Medio Oriente', 'UY', 'AR', 'BR', 'MX', 'CL')),
  category TEXT NOT NULL,
  tags TEXT NOT NULL DEFAULT '[]',
  published_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  is_featured INTEGER NOT NULL DEFAULT 0 CHECK (is_featured IN (0, 1)),
  is_impact INTEGER NOT NULL DEFAULT 0 CHECK (is_impact IN (0, 1)),
  views INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_articles_slug ON articles(slug);
CREATE INDEX IF NOT EXISTS idx_articles_published_at ON articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_region ON articles(region);
CREATE INDEX IF NOT EXISTS idx_articles_is_featured ON articles(is_featured);
CREATE INDEX IF NOT EXISTS idx_articles_is_impact ON articles(is_impact);
